title: "practice everything"
author: "huang"
description: "Really, every thing"
#subheading: "Really cool blog about ... something"
more: "read more"
# url: "huangjinhui81@gmail.com"
#baseurl: "/contrast" # comment out if in root directory

comments:
    disqus: "huangjinhui"
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  # - github: "https://github.com/huangjinhui/"
  # - twitter: "https://twitter.com/me/"
  # - google-plus: "https://plus.google.com/+me"
  # - reddit: "https://www.reddit.com/user/me/"
  # - youtube: "https://www.youtube.com/user/me"
  # - steam: "http://steamcommunity.com/id/me/"

paginate: 10
excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]

markdown: redcarpet
